language: python
matrix:
  include:
  - python: 3.7
  - python: 3.8
install:
- pip install -r test_requirements.txt
- pip install coveralls
- gem install mdl
before_script:
- cp config.py.template config.py
- mkdir logs; touch logs/quiz_ext.log
script:
- flake8
- black --check . --exclude "migrations"
- mdl .
- coverage run -m unittest discover
after_success:
- coveralls
notifications:
  slack:
    secure: aRGf2DibJ1ErSNyY2fNt6EGH9bBjoQbc0O3zL8UMu1+rMk8fM50WqiCNZt+eNlqIUjMvd+I/M0jdG4LOjrItEPexUMKVAZOU1fmuy+2gGK0dPM/4vysLCRybyoj9vr7488E2mttadNb7HxUgUyeD2auXuEstihW4topLKroCYDw3asaGXmGdE2Dtx5X52ukA6OirNmhGwfxBf6bUJpqMC3r1PD/E8Krh3GURIW4L7JQGcwGOIUYkGOGFvZbqZJHFvfZsbfZByL91m9YTAaFEDj/l6TffDL5Tk3oG9q3PHRY9a9Rpo8Cn7ZPhBvssGirVnhDBaG7pYZ/YdRRpVW2+Tr2RU0ZV1wJPwJkRWM22mRmC14yZyU3gpPmugpV1M+cD/2ySg1Tm5rQdzw1EtaWS6qqEXoB2wvWf3shs+FlRr7AHZw6gFlnd7HGaq+xddZRGYn5smYYePb/XtbpdqiqyCWkj1KFaE8z64Azx/2k73DKBhjRupaDPNqiDIyMpJ5gjzy6q4MVuGhhVxlNHxDLnB1vK1boIbsVaE3my19Y39vNwlotoWGjMO7C53BFiRe0MhVrcGGomStSlZAP+TxzDMv0Fp4RTsocTspQsxnNojcx8s23jgMjRkeYvCM0Mtsuc0FyCr/ze7z/Y7UEp6tgDEwJeJVkHuha++f7x0OAWLXc=
