"""empty message

Revision ID: 31d66406687c
Revises: bcd0a8de3c97
Create Date: 2018-01-16 10:39:13.356381

"""

# revision identifiers, used by Alembic.
revision = '31d66406687c'
down_revision = 'bcd0a8de3c97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('canvas_term_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'canvas_term_id')
    # ### end Alembic commands ###
